language: go
sudo: false
matrix:
  include:
  - os: linux 
    go: 1.10.x
    env:
    - TARGET=linux
    - ARCH=amd64
notifications:
  email: false
before_install:
- pip install --user awscli
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
script:
- make test
- make build
deploy:
  - provider: script
    script: 
      make build  &&
      make zip
    on:
      branch: master
  # - provider: script
  #   script: make zip
  #   on:
  #     branch: master
  # - provider: script
  #   script: make deploy
  #   on:
  #     branch: master
  